#include "runtime_options.h"
#include <iostream>

namespace redclaw::runtime {
void print_usage() {
    std::cout
        << "Usage: redclaw_desktop [options]\n"
        << "Options:\n"
        << "  --role <host|controller>   Runtime role mode\n"
    << "  --runtime-config <path>    Runtime deployment profile file (key=value)\n"
    << "  --target-host <value>      Signaling host when --signal-transport tcp (controller mode)\n"
    << "  --target-port <port>       Signaling TCP port (host listen / controller connect)\n"
    << "  --rendezvous-url <url>     Rendezvous endpoint URL when --signal-transport rendezvous\n"
    << "  --session-code <value>     8-char session code (required for rendezvous/dht transport)\n"
        << "  --signal-dir <path>        Shared directory for file signaling\n"
    << "  --signal-transport <file|event-log|tcp|sealed-file|rendezvous|dht>  Signaling transport mode\n"
    << "  --signal-passphrase <value>  Passphrase for sealed-file signaling\n"
    << "  --dht-bootstrap <host:port>  DHT bootstrap node (repeatable)\n"
    << "  --network-bind-address <ipv4>  Bind ICE/UPnP and DHT IPv4 to one local adapter\n"
    << "  --network-bind-ipv6-address <ipv6>  Bind DHT IPv6 to the same selected adapter\n"
    << "  --ice-udp-port <port>     Fixed local ICE UDP port (1..65535, default 55000)\n"
    << "  --dht-listen-port <port>  Fixed local UDP listen port for DHT (0 means auto)\n"
    << "  --dht-poll-interval-ms <value>  DHT remote signal fetch interval (250..60000, default 1000)\n"
    << "  --dht-publish-retry-ms <value>  DHT publish retry interval after failure (1000..120000, default 5000)\n"
    << "  --enable-port-mapping      Attempt UPnP mapping for the configured ICE UDP port\n"
    << "  --disable-ipv6-candidates  Disable IPv6 candidate diagnostics/preference\n"
    << "  --allow-remote-diagnostics  Allow peer log snapshot/follow requests (Release is deny by default)\n"
    << "  --allow-remote-input  Allow the connected peer to control the ordinary user desktop\n"
    << "  --allow-remote-agent  Allow the connected peer to use registered development Agents\n"
    << "  --agent-project-manifest <path>  Local opaque-id project registration manifest\n"
    << "  --helper-role <off|client|lan-helper|relay>  Local helper role\n"
        << "  --ice-server <uri>         ICE server URI (repeatable)\n"
        << "  --ice-server-file <path>   Read ICE server URIs from a local file\n"
        << "  --enable-ice-tcp           Enable ICE TCP candidates\n"
        << "  --stream-smoke             Enable P0 desktop preview stream smoke path\n"
        << "  --stream-require-capture   Require at least one real captured desktop frame in stream smoke\n"
        << "  --stream-qa-native-size    Local Host QA: encode the full capture content, independent of viewport\n"
        << "  --gui-runtime-stdio       Local GUI child: Control V2 on stdout, diagnostics on stderr\n"
        << "  --stream-qa-drop-one-media-fragment  QA: Controller drops one multipart media fragment\n"
        << "  --stream-qa-force-required-channel-close <media|control>\n"
        << "                             QA: Controller closes one required channel after stable playback\n"
        << "  --stream-qa-incomplete-feedback-class <fresh|delayed|expired|stale-revision>  QA feedback timing/class\n"
        << "  --agent-qa-force-channel-close-after-event\n"
        << "                             Debug QA: close only Agent channel after first task event\n"
        << "  --stream-preview-width <value>  Preview width for smoke stream (16..640, default 160)\n"
        << "  --stream-video-max-width <value>  Max encoded video width; 0 keeps native width (default 0)\n"
        << "  --stream-frame-pipe <name> Direct live frames to a local GUI shared-memory channel\n"
        << "  --stream-navigation-pipe <name> Direct navigation thumbnails to a local GUI shared-memory channel\n"
        << "  --log-dir <path>           Local rolling-log directory\n"
        << "  --run-id <value>           Correlation id for integration evidence\n"
        << "  --enable-debug-control     Enable current-user local GUI debug control\n"
        << "  --input-diagnostics        Debug-only bounded input delivery evidence; requires stream smoke\n"
        << "  --debug-control-name <value>  Override local debug control endpoint name\n"
        << "  --enable-agent-control     Enable current-user typed normal-Agent control\n"
        << "  --enable-workspace-control Enable current-user terminal/file/clipboard API\n"
        << "  --workspace-control-name   Local workspace pipe name (GUI only)\n"
        << "  --agent-control-name <value>  Override local normal-Agent control endpoint\n"
        << "  --coordination-journal-path <path>  Override owner-local coordination journal\n"
        << "  --coordination-git-sha <hex>  Record the expected local Git identity in the journal\n"
        << "  --signal-timeout-seconds <value>  Fail if signaling not completed in time (0 disables)\n"
        << "  --run-seconds <value>      Runtime duration; 0 means long-running\n"
        << "  --cli                      Force CLI mode (skip GUI shell launch)\n"
        << "  --help                     Show this help\n";
}

}  // namespace redclaw::runtime
