if(WIN32)
  find_path(FFMPEG_INCLUDE_DIRS libavcodec/avcodec.h REQUIRED)
  set(FFMPEG_LIBRARIES)
  foreach(component avcodec avutil swscale swresample)
    find_library(FFMPEG_${component}_LIBRARY NAMES ${component} REQUIRED)
    list(APPEND FFMPEG_LIBRARIES "${FFMPEG_${component}_LIBRARY}")
  endforeach()
else()
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(LATENCY_FFMPEG REQUIRED IMPORTED_TARGET
    libavcodec libavutil libswscale libswresample)
  set(FFMPEG_INCLUDE_DIRS ${LATENCY_FFMPEG_INCLUDE_DIRS})
  set(FFMPEG_LIBRARIES PkgConfig::LATENCY_FFMPEG)
  set(FFMPEG_LIBRARY_DIRS ${LATENCY_FFMPEG_LIBRARY_DIRS})
endif()
set(FFMPEG_FOUND TRUE)
